/**
 * Style Dictionary Configuration
 *
 * @what トークンJSONからCSS変数とTypeScript型を生成
 * @why コードとデザインの一貫性を保証し、型安全なトークン使用を可能にする
 * @failure 非定義トークンの使用はTypeScriptの型チェックで検出される
 */

import StyleDictionary from 'style-dictionary';

/**
 * カスタムフォーマット: TypeScript用の構造化されたオブジェクト
 * フラットなexport constではなく、ネストされたオブジェクト構造を生成
 */
StyleDictionary.registerFormat({
	name: 'typescript/nested-object',
	format: ({ dictionary, file }) => {
		/**
		 * ネストされたオブジェクトにトークンを設定
		 * @param {object} obj - 対象オブジェクト
		 * @param {string[]} path - Style Dictionaryのtoken.path配列
		 * @param {*} value - トークン値
		 */
		const setNestedValue = (obj, path, value) => {
			let current = obj;
			for (let i = 0; i < path.length - 1; i++) {
				const key = path[i];
				if (!(key in current)) {
					current[key] = {};
				}
				current = current[key];
			}
			current[path[path.length - 1]] = value;
		};

		// 構造化されたトークンオブジェクトを構築
		const nestedTokens = {};

		dictionary.allTokens.forEach((token) => {
			// token.path は Style Dictionary が提供する配列
			// 例: ["color", "gray", "50"]
			setNestedValue(nestedTokens, token.path, token.value);
		});

		// ファイル内容を生成
		let output = `/**
 * Design System Tokens - Structured Export
 *
 * @generated by Style Dictionary
 * @description 構造化されたトークンオブジェクト。IDEオートコンプリート対応。
 *
 * 使用例:
 *   import { tokens } from '@design-system/tokens';
 *   const bgColor = tokens.color.surface.page;
 *   const headingStyle = tokens.typography.heading.xl;
 */

`;

		// 個別のexport const（後方互換性のため維持）
		dictionary.allTokens.forEach((token) => {
			output += `export const ${token.name} = ${JSON.stringify(token.value)};\n`;
		});

		// 構造化されたエクスポート
		output += `\n/**
 * 構造化されたトークンオブジェクト
 * ネストされた構造でアクセス可能: tokens.color.surface.page
 */
export const tokens = ${JSON.stringify(nestedTokens, null, 2)} as const;

/**
 * トークン型定義
 */
export type Tokens = typeof tokens;
`;

		return output;
	},
});

const config = {
	source: ['design-tokens/**/*.json'],
	log: {
		verbosity: 'verbose',
	},
	platforms: {
		css: {
			transformGroup: 'css',
			prefix: 'pt',
			buildPath: 'src/styles/generated/',
			files: [
				{
					destination: 'tokens.css',
					format: 'css/variables',
					options: {
						outputReferences: true,
					},
				},
			],
		},
		scss: {
			transformGroup: 'scss',
			prefix: 'pt',
			buildPath: 'src/styles/generated/',
			files: [
				{
					destination: '_tokens.scss',
					format: 'scss/variables',
					options: {
						outputReferences: true,
					},
				},
			],
		},
		ts: {
			transformGroup: 'js',
			prefix: 'pt',
			buildPath: 'src/design-system/',
			files: [
				{
					destination: 'tokens.ts',
					format: 'typescript/nested-object',
				},
			],
		},
	},
};

const sd = new StyleDictionary(config);
await sd.buildAllPlatforms();

console.log('\n✅ Design tokens built successfully!');
console.log('   - src/styles/generated/tokens.css');
console.log('   - src/styles/generated/_tokens.scss');
console.log('   - src/design-system/tokens.ts (structured)');
