/**
 * Style Dictionary Configuration
 *
 * @what トークンJSONからCSS変数とTypeScript型を生成
 * @why コードとデザインの一貫性を保証し、型安全なトークン使用を可能にする
 * @failure 非定義トークンの使用はTypeScriptの型チェックで検出される
 */

import StyleDictionary from 'style-dictionary';

/**
 * ネストされたオブジェクトにトークンを設定
 */
const setNestedValue = (obj, path, value) => {
	let current = obj;
	for (let i = 0; i < path.length - 1; i++) {
		const key = path[i];
		if (!(key in current)) {
			current[key] = {};
		}
		current = current[key];
	}
	current[path[path.length - 1]] = value;
};

/**
 * カテゴリ別フォーマットを生成するファクトリ関数
 */
const createCategoryFormat = (categoryName, rootKeys) => ({
	name: `typescript/${categoryName}`,
	format: ({ dictionary }) => {
		const nestedTokens = {};

		dictionary.allTokens.forEach((token) => {
			// ルートキーでフィルタリング
			if (rootKeys.includes(token.path[0])) {
				setNestedValue(nestedTokens, token.path, token.value);
			}
		});

		return `/**
 * Design System Tokens - ${categoryName}
 * @generated by Style Dictionary
 */

export const ${categoryName} = ${JSON.stringify(nestedTokens, null, 2)} as const;

export type ${categoryName.charAt(0).toUpperCase() + categoryName.slice(1)}Tokens = typeof ${categoryName};
`;
	},
});

/**
 * index.ts 用フォーマット
 */
StyleDictionary.registerFormat({
	name: 'typescript/index',
	format: () => `/**
 * Design System Tokens - Unified Export
 * @generated by Style Dictionary
 *
 * 使用例:
 *   import { tokens } from '@design-system/tokens';
 *   const bgColor = tokens.color.surface.page;
 *   const headingStyle = tokens.typography.heading.xl;
 */

export { colors } from './colors';
export { typography } from './typography';
export { spacing } from './spacing';
export { effects } from './effects';
export { components } from './components';

// 統合トークンオブジェクト
import { colors } from './colors';
import { typography } from './typography';
import { spacing } from './spacing';
import { effects } from './effects';
import { components } from './components';

export const tokens = {
	...colors,
	...typography,
	...spacing,
	...effects,
	...components,
} as const;

export type Tokens = typeof tokens;
`,
});

// カテゴリ別フォーマットを登録
StyleDictionary.registerFormat(
	createCategoryFormat('colors', ['color'])
);
StyleDictionary.registerFormat(
	createCategoryFormat('typography', ['font', 'typography'])
);
StyleDictionary.registerFormat(
	createCategoryFormat('spacing', ['space', 'spacing'])
);
StyleDictionary.registerFormat(
	createCategoryFormat('effects', ['radius', 'border', 'shadow', 'duration', 'easing', 'elevation', 'semantic-border', 'motion'])
);
StyleDictionary.registerFormat(
	createCategoryFormat('components', ['avatar', 'badge', 'button', 'card', 'chip', 'grid', 'heading', 'icon', 'radio-button', 'spinner', 'stack', 'surface', 'text', 'type-chip'])
);

const config = {
	source: ['design-tokens/**/*.json'],
	log: {
		verbosity: 'verbose',
	},
	platforms: {
		css: {
			transformGroup: 'css',
			prefix: 'pt',
			buildPath: 'src/styles/generated/',
			files: [
				{
					destination: 'tokens.css',
					format: 'css/variables',
					options: {
						outputReferences: true,
					},
				},
			],
		},
		scss: {
			transformGroup: 'scss',
			prefix: 'pt',
			buildPath: 'src/styles/generated/',
			files: [
				{
					destination: '_tokens.scss',
					format: 'scss/variables',
					options: {
						outputReferences: true,
					},
				},
			],
		},
		ts: {
			transformGroup: 'js',
			prefix: 'pt',
			buildPath: 'src/design-system/tokens/',
			files: [
				{ destination: 'colors.ts', format: 'typescript/colors' },
				{ destination: 'typography.ts', format: 'typescript/typography' },
				{ destination: 'spacing.ts', format: 'typescript/spacing' },
				{ destination: 'effects.ts', format: 'typescript/effects' },
				{ destination: 'components.ts', format: 'typescript/components' },
				{ destination: 'index.ts', format: 'typescript/index' },
			],
		},
	},
};

const sd = new StyleDictionary(config);
await sd.buildAllPlatforms();

console.log('\n✅ Design tokens built successfully!');
console.log('   - src/styles/generated/tokens.css');
console.log('   - src/styles/generated/_tokens.scss');
console.log('   - src/design-system/tokens/');
console.log('     ├── colors.ts');
console.log('     ├── typography.ts');
console.log('     ├── spacing.ts');
console.log('     ├── effects.ts');
console.log('     ├── components.ts');
console.log('     └── index.ts');

