/**
 * Icon component variant types
 * @generated by scripts/tokens/generate-types-from-tokens.mjs
 * Do not edit manually - run `npm run tokens:build` to regenerate
 */

import { PokemonType } from '@domain/type-chart';

export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

/** Available icon size variants */
export const ICON_SIZES: IconSize[] = ['xs', 'sm', 'md', 'lg', 'xl'];

export type IconColor = PokemonType | 'inverse';
