/**
 * Design System Tokens - Structured Export
 *
 * @generated by Style Dictionary
 * @description 構造化されたトークンオブジェクト。IDEオートコンプリート対応。
 *
 * 使用例:
 *   import { tokens } from '@design-system/tokens';
 *   const bgColor = tokens.color.surface.page;
 *   const headingStyle = tokens.typography.heading.xl;
 */

export const PtColorPokemonNormal50 = "#f6f6f2";
export const PtColorPokemonNormal100 = "#ecece4";
export const PtColorPokemonNormal200 = "#d8d7c6";
export const PtColorPokemonNormal300 = "#c4c3a9";
export const PtColorPokemonNormal400 = "#b0af8b";
export const PtColorPokemonNormal500 = "#a8a77a";
export const PtColorPokemonNormal600 = "#868662";
export const PtColorPokemonNormal700 = "#656449";
export const PtColorPokemonNormal800 = "#434331";
export const PtColorPokemonNormal900 = "#222118";
export const PtColorPokemonNormal950 = "#11110c";
export const PtColorPokemonFire50 = "#fef2ea";
export const PtColorPokemonFire100 = "#fce6d5";
export const PtColorPokemonFire200 = "#f9ccac";
export const PtColorPokemonFire300 = "#f5b282";
export const PtColorPokemonFire400 = "#f29959";
export const PtColorPokemonFire500 = "#ee8130";
export const PtColorPokemonFire600 = "#be6726";
export const PtColorPokemonFire700 = "#8f4d1d";
export const PtColorPokemonFire800 = "#5f3413";
export const PtColorPokemonFire900 = "#301a0a";
export const PtColorPokemonFire950 = "#180d05";
export const PtColorPokemonWater50 = "#eff4fe";
export const PtColorPokemonWater100 = "#e0e9fc";
export const PtColorPokemonWater200 = "#c1d2fa";
export const PtColorPokemonWater300 = "#a1bcf7";
export const PtColorPokemonWater400 = "#82a6f4";
export const PtColorPokemonWater500 = "#6390f0";
export const PtColorPokemonWater600 = "#4f73c0";
export const PtColorPokemonWater700 = "#3b5690";
export const PtColorPokemonWater800 = "#283a60";
export const PtColorPokemonWater900 = "#141d30";
export const PtColorPokemonWater950 = "#0a0e18";
export const PtColorPokemonElectric50 = "#fefbea";
export const PtColorPokemonElectric100 = "#fef6d5";
export const PtColorPokemonElectric200 = "#fdecaa";
export const PtColorPokemonElectric300 = "#fce280";
export const PtColorPokemonElectric400 = "#fad956";
export const PtColorPokemonElectric500 = "#f7d02c";
export const PtColorPokemonElectric600 = "#c6a623";
export const PtColorPokemonElectric700 = "#947d1a";
export const PtColorPokemonElectric800 = "#635312";
export const PtColorPokemonElectric900 = "#312a09";
export const PtColorPokemonElectric950 = "#191504";
export const PtColorPokemonGrass50 = "#f2f9ed";
export const PtColorPokemonGrass100 = "#e4f4db";
export const PtColorPokemonGrass200 = "#c9e9b8";
export const PtColorPokemonGrass300 = "#aede94";
export const PtColorPokemonGrass400 = "#94d371";
export const PtColorPokemonGrass500 = "#7ac74c";
export const PtColorPokemonGrass600 = "#629f3d";
export const PtColorPokemonGrass700 = "#49772e";
export const PtColorPokemonGrass800 = "#314f1e";
export const PtColorPokemonGrass900 = "#18280f";
export const PtColorPokemonGrass950 = "#0c1408";
export const PtColorPokemonIce50 = "#f4fbfb";
export const PtColorPokemonIce100 = "#eaf7f7";
export const PtColorPokemonIce200 = "#d5efee";
export const PtColorPokemonIce300 = "#c0e7e5";
export const PtColorPokemonIce400 = "#abe0dd";
export const PtColorPokemonIce500 = "#96d9d6";
export const PtColorPokemonIce600 = "#78aeab";
export const PtColorPokemonIce700 = "#5a8280";
export const PtColorPokemonIce800 = "#3c5756";
export const PtColorPokemonIce900 = "#1e2b2b";
export const PtColorPokemonIce950 = "#0f1616";
export const PtColorPokemonFighting50 = "#f9eaeb";
export const PtColorPokemonFighting100 = "#f3d5d6";
export const PtColorPokemonFighting200 = "#e7abad";
export const PtColorPokemonFighting300 = "#db8285";
export const PtColorPokemonFighting400 = "#cf585c";
export const PtColorPokemonFighting500 = "#c22e28";
export const PtColorPokemonFighting600 = "#9b2520";
export const PtColorPokemonFighting700 = "#741c18";
export const PtColorPokemonFighting800 = "#4e1210";
export const PtColorPokemonFighting900 = "#270908";
export const PtColorPokemonFighting950 = "#130504";
export const PtColorPokemonPoison50 = "#f6ecf6";
export const PtColorPokemonPoison100 = "#edd8ec";
export const PtColorPokemonPoison200 = "#dbb2da";
export const PtColorPokemonPoison300 = "#c98cc7";
export const PtColorPokemonPoison400 = "#b765b5";
export const PtColorPokemonPoison500 = "#a33ea1";
export const PtColorPokemonPoison600 = "#823281";
export const PtColorPokemonPoison700 = "#622561";
export const PtColorPokemonPoison800 = "#411940";
export const PtColorPokemonPoison900 = "#210c20";
export const PtColorPokemonPoison950 = "#100610";
export const PtColorPokemonGround50 = "#fcf9f0";
export const PtColorPokemonGround100 = "#f9f2e0";
export const PtColorPokemonGround200 = "#f3e6c1";
export const PtColorPokemonGround300 = "#edd9a3";
export const PtColorPokemonGround400 = "#e7cd84";
export const PtColorPokemonGround500 = "#e2bf65";
export const PtColorPokemonGround600 = "#b59951";
export const PtColorPokemonGround700 = "#88733d";
export const PtColorPokemonGround800 = "#5a4c28";
export const PtColorPokemonGround900 = "#2d2614";
export const PtColorPokemonGround950 = "#17130a";
export const PtColorPokemonFlying50 = "#f6f4fe";
export const PtColorPokemonFlying100 = "#ede9fc";
export const PtColorPokemonFlying200 = "#dbd2f9";
export const PtColorPokemonFlying300 = "#c9bcf6";
export const PtColorPokemonFlying400 = "#b7a5f3";
export const PtColorPokemonFlying500 = "#a98ff3";
export const PtColorPokemonFlying600 = "#8772c2";
export const PtColorPokemonFlying700 = "#655692";
export const PtColorPokemonFlying800 = "#443961";
export const PtColorPokemonFlying900 = "#221d31";
export const PtColorPokemonFlying950 = "#110e18";
export const PtColorPokemonPsychic50 = "#ffeef3";
export const PtColorPokemonPsychic100 = "#ffdde7";
export const PtColorPokemonPsychic200 = "#ffbbce";
export const PtColorPokemonPsychic300 = "#ff99b6";
export const PtColorPokemonPsychic400 = "#fb779e";
export const PtColorPokemonPsychic500 = "#f95587";
export const PtColorPokemonPsychic600 = "#c7446c";
export const PtColorPokemonPsychic700 = "#953351";
export const PtColorPokemonPsychic800 = "#642236";
export const PtColorPokemonPsychic900 = "#32111b";
export const PtColorPokemonPsychic950 = "#19080d";
export const PtColorPokemonBug50 = "#f6f8e8";
export const PtColorPokemonBug100 = "#edf1d1";
export const PtColorPokemonBug200 = "#dce4a3";
export const PtColorPokemonBug300 = "#cad676";
export const PtColorPokemonBug400 = "#b8c948";
export const PtColorPokemonBug500 = "#a6b91a";
export const PtColorPokemonBug600 = "#859415";
export const PtColorPokemonBug700 = "#646f10";
export const PtColorPokemonBug800 = "#424a0b";
export const PtColorPokemonBug900 = "#212505";
export const PtColorPokemonBug950 = "#101203";
export const PtColorPokemonRock50 = "#f8f6eb";
export const PtColorPokemonRock100 = "#f1ecd7";
export const PtColorPokemonRock200 = "#e3d9af";
export const PtColorPokemonRock300 = "#d5c687";
export const PtColorPokemonRock400 = "#c6b35e";
export const PtColorPokemonRock500 = "#b6a136";
export const PtColorPokemonRock600 = "#92812b";
export const PtColorPokemonRock700 = "#6d6120";
export const PtColorPokemonRock800 = "#494016";
export const PtColorPokemonRock900 = "#24200b";
export const PtColorPokemonRock950 = "#121005";
export const PtColorPokemonGhost50 = "#f1eef5";
export const PtColorPokemonGhost100 = "#e3deeb";
export const PtColorPokemonGhost200 = "#c7bdd6";
export const PtColorPokemonGhost300 = "#ab9cc2";
export const PtColorPokemonGhost400 = "#8f7bad";
export const PtColorPokemonGhost500 = "#735797";
export const PtColorPokemonGhost600 = "#5c4679";
export const PtColorPokemonGhost700 = "#45345b";
export const PtColorPokemonGhost800 = "#2e233c";
export const PtColorPokemonGhost900 = "#17111e";
export const PtColorPokemonGhost950 = "#0b090f";
export const PtColorPokemonDragon50 = "#f1ebfe";
export const PtColorPokemonDragon100 = "#e2d7fe";
export const PtColorPokemonDragon200 = "#c6affd";
export const PtColorPokemonDragon300 = "#a986fc";
export const PtColorPokemonDragon400 = "#8d5dfc";
export const PtColorPokemonDragon500 = "#6f35fc";
export const PtColorPokemonDragon600 = "#592aca";
export const PtColorPokemonDragon700 = "#431f97";
export const PtColorPokemonDragon800 = "#2c1565";
export const PtColorPokemonDragon900 = "#160b32";
export const PtColorPokemonDragon950 = "#0b0519";
export const PtColorPokemonSteel50 = "#f8f8fa";
export const PtColorPokemonSteel100 = "#f1f1f5";
export const PtColorPokemonSteel200 = "#e2e2eb";
export const PtColorPokemonSteel300 = "#d4d4e1";
export const PtColorPokemonSteel400 = "#c5c5d8";
export const PtColorPokemonSteel500 = "#b7b7ce";
export const PtColorPokemonSteel600 = "#9292a5";
export const PtColorPokemonSteel700 = "#6e6e7c";
export const PtColorPokemonSteel800 = "#494952";
export const PtColorPokemonSteel900 = "#252529";
export const PtColorPokemonSteel950 = "#121215";
export const PtColorPokemonDark50 = "#f1eeed";
export const PtColorPokemonDark100 = "#e3dedb";
export const PtColorPokemonDark200 = "#c6bcb7";
export const PtColorPokemonDark300 = "#a99b93";
export const PtColorPokemonDark400 = "#8d796e";
export const PtColorPokemonDark500 = "#705746";
export const PtColorPokemonDark600 = "#5a4638";
export const PtColorPokemonDark700 = "#43342a";
export const PtColorPokemonDark800 = "#2d231c";
export const PtColorPokemonDark900 = "#16110e";
export const PtColorPokemonDark950 = "#0b0907";
export const PtColorPokemonFairy50 = "#fbf3f7";
export const PtColorPokemonFairy100 = "#f7e7ee";
export const PtColorPokemonFairy200 = "#efcedd";
export const PtColorPokemonFairy300 = "#e7b6cc";
export const PtColorPokemonFairy400 = "#df9dba";
export const PtColorPokemonFairy500 = "#d685ad";
export const PtColorPokemonFairy600 = "#ab6a8a";
export const PtColorPokemonFairy700 = "#805068";
export const PtColorPokemonFairy800 = "#563545";
export const PtColorPokemonFairy900 = "#2b1b23";
export const PtColorPokemonFairy950 = "#150d11";
export const PtColorPokemonTypeNormal = "#a8a77a";
export const PtColorPokemonTypeFire = "#ee8130";
export const PtColorPokemonTypeWater = "#6390f0";
export const PtColorPokemonTypeElectric = "#f7d02c";
export const PtColorPokemonTypeGrass = "#7ac74c";
export const PtColorPokemonTypeIce = "#96d9d6";
export const PtColorPokemonTypeFighting = "#c22e28";
export const PtColorPokemonTypePoison = "#a33ea1";
export const PtColorPokemonTypeGround = "#e2bf65";
export const PtColorPokemonTypeFlying = "#a98ff3";
export const PtColorPokemonTypePsychic = "#f95587";
export const PtColorPokemonTypeBug = "#a6b91a";
export const PtColorPokemonTypeRock = "#b6a136";
export const PtColorPokemonTypeGhost = "#735797";
export const PtColorPokemonTypeDragon = "#6f35fc";
export const PtColorPokemonTypeDark = "#705746";
export const PtColorPokemonTypeSteel = "#b7b7ce";
export const PtColorPokemonTypeFairy = "#d685ad";
export const PtColorPokemonBgNormal = "#f6f6f2";
export const PtColorPokemonBgFire = "#fef2ea";
export const PtColorPokemonBgWater = "#eff4fe";
export const PtColorPokemonBgElectric = "#fefbea";
export const PtColorPokemonBgGrass = "#f2f9ed";
export const PtColorPokemonBgIce = "#f4fbfb";
export const PtColorPokemonBgFighting = "#f9eaeb";
export const PtColorPokemonBgPoison = "#f6ecf6";
export const PtColorPokemonBgGround = "#fcf9f0";
export const PtColorPokemonBgFlying = "#f6f4fe";
export const PtColorPokemonBgPsychic = "#ffeef3";
export const PtColorPokemonBgBug = "#f6f8e8";
export const PtColorPokemonBgRock = "#f8f6eb";
export const PtColorPokemonBgGhost = "#f1eef5";
export const PtColorPokemonBgDragon = "#f1ebfe";
export const PtColorPokemonBgDark = "#f1eeed";
export const PtColorPokemonBgSteel = "#f8f8fa";
export const PtColorPokemonBgFairy = "#fbf3f7";
export const PtColorPokemonTextNormal = "#656449";
export const PtColorPokemonTextFire = "#8f4d1d";
export const PtColorPokemonTextWater = "#3b5690";
export const PtColorPokemonTextElectric = "#947d1a";
export const PtColorPokemonTextGrass = "#49772e";
export const PtColorPokemonTextIce = "#5a8280";
export const PtColorPokemonTextFighting = "#741c18";
export const PtColorPokemonTextPoison = "#622561";
export const PtColorPokemonTextGround = "#88733d";
export const PtColorPokemonTextFlying = "#655692";
export const PtColorPokemonTextPsychic = "#953351";
export const PtColorPokemonTextBug = "#646f10";
export const PtColorPokemonTextRock = "#6d6120";
export const PtColorPokemonTextGhost = "#45345b";
export const PtColorPokemonTextDragon = "#431f97";
export const PtColorPokemonTextDark = "#43342a";
export const PtColorPokemonTextSteel = "#6e6e7c";
export const PtColorPokemonTextFairy = "#805068";
export const PtColorGray50 = "#f9fafb";
export const PtColorGray100 = "#f3f4f6";
export const PtColorGray200 = "#e5e7eb";
export const PtColorGray300 = "#d1d5db";
export const PtColorGray400 = "#9ca3af";
export const PtColorGray500 = "#6b7280";
export const PtColorGray600 = "#4b5563";
export const PtColorGray700 = "#374151";
export const PtColorGray800 = "#1f2937";
export const PtColorGray900 = "#111827";
export const PtColorGray950 = "#030712";
export const PtColorLime50 = "#f7fee7";
export const PtColorLime100 = "#ecfccb";
export const PtColorLime200 = "#d9f99d";
export const PtColorLime300 = "#bef264";
export const PtColorLime400 = "#a3e635";
export const PtColorLime500 = "#84cc16";
export const PtColorLime600 = "#65a30d";
export const PtColorLime700 = "#4d7c0f";
export const PtColorLime800 = "#3f6212";
export const PtColorLime900 = "#365314";
export const PtColorLime950 = "#1a2e05";
export const PtColorRed50 = "#fef2f2";
export const PtColorRed100 = "#fee2e2";
export const PtColorRed200 = "#fecaca";
export const PtColorRed300 = "#fca5a5";
export const PtColorRed400 = "#f87171";
export const PtColorRed500 = "#ef4444";
export const PtColorRed600 = "#dc2626";
export const PtColorRed700 = "#b91c1c";
export const PtColorRed800 = "#991b1b";
export const PtColorRed900 = "#7f1d1d";
export const PtColorRed950 = "#450a0a";
export const PtColorWhite = "#ffffff";
export const PtColorBlack = "#000000";
export const PtColorResultWinDefault = "#84cc16";
export const PtColorResultWinSubtle = "#ecfccb";
export const PtColorResultWinStrong = "#4d7c0f";
export const PtColorResultLoseDefault = "#ef4444";
export const PtColorResultLoseSubtle = "#fee2e2";
export const PtColorResultLoseStrong = "#b91c1c";
export const PtColorSurfacePage = "#f9fafb";
export const PtColorSurfaceCard = "#ffffff";
export const PtColorSurfaceElevated = "#ffffff";
export const PtColorSurfaceHovered = "#f3f4f6";
export const PtColorSurfacePressed = "#e5e7eb";
export const PtColorTextPrimary = "#1f2937";
export const PtColorTextSecondary = "#6b7280";
export const PtColorTextDisabled = "#9ca3af";
export const PtColorTextInverse = "#ffffff";
export const PtColorBorderDefault = "#e5e7eb";
export const PtColorBorderSubtle = "#f3f4f6";
export const PtColorBorderFocused = "#4b5563";
export const PtRadiusNone = "0";
export const PtRadiusSm = "0.25rem";
export const PtRadiusMd = "0.5rem";
export const PtRadiusLg = "0.75rem";
export const PtRadiusXl = "1rem";
export const PtRadius2xl = "1.5rem";
export const PtRadiusFull = "9999px";
export const PtBorderWidthNone = "0";
export const PtBorderWidthSm = "1px";
export const PtBorderWidthMd = "2px";
export const PtBorderWidthLg = "4px";
export const PtShadowNone = "none";
export const PtShadowSm = "0 1px 2px 0 rgb(0 0 0 / 0.05)";
export const PtShadowMd = "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)";
export const PtShadowLg = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";
export const PtShadowXl = "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)";
export const PtShadow2xl = "0 25px 50px -12px rgb(0 0 0 / 0.25)";
export const PtDurationFast = "100ms";
export const PtDurationNormal = "200ms";
export const PtDurationSlow = "300ms";
export const PtDurationSlower = "500ms";
export const PtEasingDefault = "cubic-bezier(0.4, 0, 0.2, 1)";
export const PtEasingIn = "cubic-bezier(0.4, 0, 1, 1)";
export const PtEasingOut = "cubic-bezier(0, 0, 0.2, 1)";
export const PtEasingInOut = "cubic-bezier(0.4, 0, 0.2, 1)";
export const PtSpace0 = "0";
export const PtSpace1 = "0.25rem";
export const PtSpace2 = "0.5rem";
export const PtSpace3 = "0.75rem";
export const PtSpace4 = "1rem";
export const PtSpace5 = "1.25rem";
export const PtSpace6 = "1.5rem";
export const PtSpace8 = "2rem";
export const PtSpace10 = "2.5rem";
export const PtSpace12 = "3rem";
export const PtSpace16 = "4rem";
export const PtSpace20 = "5rem";
export const PtFontFamilySans = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtFontFamilyMono = "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace";
export const PtFontSizeXs = "0.75rem";
export const PtFontSizeSm = "0.875rem";
export const PtFontSizeMd = "1rem";
export const PtFontSizeLg = "1.125rem";
export const PtFontSizeXl = "1.25rem";
export const PtFontSize2xl = "1.5rem";
export const PtFontSize3xl = "1.875rem";
export const PtFontSize4xl = "2.25rem";
export const PtFontWeightNormal = "400";
export const PtFontWeightMedium = "500";
export const PtFontWeightSemibold = "600";
export const PtFontWeightBold = "700";
export const PtFontLineHeightTight = "1.25";
export const PtFontLineHeightNormal = "1.5";
export const PtFontLineHeightRelaxed = "1.75";
export const PtElevationNone = "none";
export const PtElevationRaised = "0 1px 2px 0 rgb(0 0 0 / 0.05)";
export const PtElevationOverlay = "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)";
export const PtElevationModal = "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)";
export const PtElevationToast = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";
export const PtSemanticBorderRadiusNone = "0";
export const PtSemanticBorderRadiusSm = "0.25rem";
export const PtSemanticBorderRadiusMd = "0.5rem";
export const PtSemanticBorderRadiusLg = "0.75rem";
export const PtSemanticBorderRadiusPill = "9999px";
export const PtSemanticBorderWidthNone = "0";
export const PtSemanticBorderWidthDefault = "1px";
export const PtSemanticBorderWidthThick = "2px";
export const PtMotionDurationInstant = "100ms";
export const PtMotionDurationQuick = "200ms";
export const PtMotionDurationModerate = "300ms";
export const PtMotionDurationDeliberate = "500ms";
export const PtMotionEasingDefault = "cubic-bezier(0.4, 0, 0.2, 1)";
export const PtMotionEasingEnter = "cubic-bezier(0, 0, 0.2, 1)";
export const PtMotionEasingExit = "cubic-bezier(0.4, 0, 1, 1)";
export const PtSpacingContentXs = "0.25rem";
export const PtSpacingContentSm = "0.5rem";
export const PtSpacingContentMd = "1rem";
export const PtSpacingContentLg = "1.5rem";
export const PtSpacingContentXl = "2rem";
export const PtSpacingLayoutSection = "3rem";
export const PtSpacingLayoutPage = "4rem";
export const PtSpacingGapXs = "0.25rem";
export const PtSpacingGapSm = "0.5rem";
export const PtSpacingGapMd = "1rem";
export const PtSpacingGapLg = "1.5rem";
export const PtTypographyHeadingXlFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyHeadingXlFontSize = "2.25rem";
export const PtTypographyHeadingXlFontWeight = "700";
export const PtTypographyHeadingXlLineHeight = "1.25";
export const PtTypographyHeadingLgFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyHeadingLgFontSize = "1.5rem";
export const PtTypographyHeadingLgFontWeight = "600";
export const PtTypographyHeadingLgLineHeight = "1.25";
export const PtTypographyHeadingMdFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyHeadingMdFontSize = "1.25rem";
export const PtTypographyHeadingMdFontWeight = "600";
export const PtTypographyHeadingMdLineHeight = "1.5";
export const PtTypographyHeadingSmFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyHeadingSmFontSize = "1.125rem";
export const PtTypographyHeadingSmFontWeight = "500";
export const PtTypographyHeadingSmLineHeight = "1.5";
export const PtTypographyBodyLgFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyBodyLgFontSize = "1.125rem";
export const PtTypographyBodyLgFontWeight = "400";
export const PtTypographyBodyLgLineHeight = "1.75";
export const PtTypographyBodyMdFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyBodyMdFontSize = "1rem";
export const PtTypographyBodyMdFontWeight = "400";
export const PtTypographyBodyMdLineHeight = "1.5";
export const PtTypographyBodySmFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyBodySmFontSize = "0.875rem";
export const PtTypographyBodySmFontWeight = "400";
export const PtTypographyBodySmLineHeight = "1.5";
export const PtTypographyLabelMdFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyLabelMdFontSize = "0.875rem";
export const PtTypographyLabelMdFontWeight = "500";
export const PtTypographyLabelMdLineHeight = "1.25";
export const PtTypographyLabelSmFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyLabelSmFontSize = "0.75rem";
export const PtTypographyLabelSmFontWeight = "500";
export const PtTypographyLabelSmLineHeight = "1.25";
export const PtTypographyLabelXsFontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif";
export const PtTypographyLabelXsFontSize = "0.75rem";
export const PtTypographyLabelXsFontWeight = "400";
export const PtTypographyLabelXsLineHeight = "1.25";
export const PtTypographyCodeMdFontFamily = "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace";
export const PtTypographyCodeMdFontSize = "0.875rem";
export const PtTypographyCodeMdFontWeight = "400";
export const PtTypographyCodeMdLineHeight = "1.5";
export const PtBadgeNeutralBg = "#f3f4f6";
export const PtBadgeNeutralText = "#1f2937";
export const PtBadgeWinBg = "#ecfccb";
export const PtBadgeWinText = "#4d7c0f";
export const PtBadgeLoseBg = "#fee2e2";
export const PtBadgeLoseText = "#b91c1c";
export const PtBadgePaddingX = "0.5rem";
export const PtBadgePaddingY = "0.25rem";
export const PtBadgeRadius = "0.25rem";
export const PtButtonPrimaryBgDefault = "#1f2937";
export const PtButtonPrimaryBgHover = "#374151";
export const PtButtonPrimaryBgPressed = "#111827";
export const PtButtonPrimaryBgDisabled = "#e5e7eb";
export const PtButtonPrimaryTextDefault = "#ffffff";
export const PtButtonPrimaryTextDisabled = "#9ca3af";
export const PtButtonPrimaryBorderDefault = "#00000000";
export const PtButtonPrimaryBorderFocus = "#4b5563";
export const PtButtonSecondaryBgDefault = "#00000000";
export const PtButtonSecondaryBgHover = "#f3f4f6";
export const PtButtonSecondaryBgPressed = "#e5e7eb";
export const PtButtonSecondaryBgDisabled = "#00000000";
export const PtButtonSecondaryTextDefault = "#1f2937";
export const PtButtonSecondaryTextDisabled = "#9ca3af";
export const PtButtonSecondaryBorderDefault = "#e5e7eb";
export const PtButtonSecondaryBorderHover = "#4b5563";
export const PtButtonSecondaryBorderFocus = "#4b5563";
export const PtButtonGhostBgDefault = "#00000000";
export const PtButtonGhostBgHover = "#f3f4f6";
export const PtButtonGhostBgPressed = "#e5e7eb";
export const PtButtonGhostBgDisabled = "#00000000";
export const PtButtonGhostTextDefault = "#1f2937";
export const PtButtonGhostTextDisabled = "#9ca3af";
export const PtButtonGhostBorderDefault = "#00000000";
export const PtButtonGhostBorderFocus = "#4b5563";
export const PtCardBgDefault = "#ffffff";
export const PtCardBgHover = "#f3f4f6";
export const PtCardBorderDefault = "#f3f4f6";
export const PtCardTextTitle = "#1f2937";
export const PtCardTextBody = "#6b7280";
export const PtCardShadowFlat = "none";
export const PtCardShadowRaised = "0 1px 2px 0 rgb(0 0 0 / 0.05)";
export const PtCardShadowOverlay = "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)";
export const PtCardPaddingSm = "0.5rem";
export const PtCardPaddingMd = "1rem";
export const PtCardPaddingLg = "1.5rem";
export const PtCardRadius = "0.75rem";

/**
 * 構造化されたトークンオブジェクト
 * ネストされた構造でアクセス可能: tokens.color.surface.page
 */
export const tokens = {
  "color": {
    "pokemon": {
      "normal": {
        "50": "#f6f6f2",
        "100": "#ecece4",
        "200": "#d8d7c6",
        "300": "#c4c3a9",
        "400": "#b0af8b",
        "500": "#a8a77a",
        "600": "#868662",
        "700": "#656449",
        "800": "#434331",
        "900": "#222118",
        "950": "#11110c"
      },
      "fire": {
        "50": "#fef2ea",
        "100": "#fce6d5",
        "200": "#f9ccac",
        "300": "#f5b282",
        "400": "#f29959",
        "500": "#ee8130",
        "600": "#be6726",
        "700": "#8f4d1d",
        "800": "#5f3413",
        "900": "#301a0a",
        "950": "#180d05"
      },
      "water": {
        "50": "#eff4fe",
        "100": "#e0e9fc",
        "200": "#c1d2fa",
        "300": "#a1bcf7",
        "400": "#82a6f4",
        "500": "#6390f0",
        "600": "#4f73c0",
        "700": "#3b5690",
        "800": "#283a60",
        "900": "#141d30",
        "950": "#0a0e18"
      },
      "electric": {
        "50": "#fefbea",
        "100": "#fef6d5",
        "200": "#fdecaa",
        "300": "#fce280",
        "400": "#fad956",
        "500": "#f7d02c",
        "600": "#c6a623",
        "700": "#947d1a",
        "800": "#635312",
        "900": "#312a09",
        "950": "#191504"
      },
      "grass": {
        "50": "#f2f9ed",
        "100": "#e4f4db",
        "200": "#c9e9b8",
        "300": "#aede94",
        "400": "#94d371",
        "500": "#7ac74c",
        "600": "#629f3d",
        "700": "#49772e",
        "800": "#314f1e",
        "900": "#18280f",
        "950": "#0c1408"
      },
      "ice": {
        "50": "#f4fbfb",
        "100": "#eaf7f7",
        "200": "#d5efee",
        "300": "#c0e7e5",
        "400": "#abe0dd",
        "500": "#96d9d6",
        "600": "#78aeab",
        "700": "#5a8280",
        "800": "#3c5756",
        "900": "#1e2b2b",
        "950": "#0f1616"
      },
      "fighting": {
        "50": "#f9eaeb",
        "100": "#f3d5d6",
        "200": "#e7abad",
        "300": "#db8285",
        "400": "#cf585c",
        "500": "#c22e28",
        "600": "#9b2520",
        "700": "#741c18",
        "800": "#4e1210",
        "900": "#270908",
        "950": "#130504"
      },
      "poison": {
        "50": "#f6ecf6",
        "100": "#edd8ec",
        "200": "#dbb2da",
        "300": "#c98cc7",
        "400": "#b765b5",
        "500": "#a33ea1",
        "600": "#823281",
        "700": "#622561",
        "800": "#411940",
        "900": "#210c20",
        "950": "#100610"
      },
      "ground": {
        "50": "#fcf9f0",
        "100": "#f9f2e0",
        "200": "#f3e6c1",
        "300": "#edd9a3",
        "400": "#e7cd84",
        "500": "#e2bf65",
        "600": "#b59951",
        "700": "#88733d",
        "800": "#5a4c28",
        "900": "#2d2614",
        "950": "#17130a"
      },
      "flying": {
        "50": "#f6f4fe",
        "100": "#ede9fc",
        "200": "#dbd2f9",
        "300": "#c9bcf6",
        "400": "#b7a5f3",
        "500": "#a98ff3",
        "600": "#8772c2",
        "700": "#655692",
        "800": "#443961",
        "900": "#221d31",
        "950": "#110e18"
      },
      "psychic": {
        "50": "#ffeef3",
        "100": "#ffdde7",
        "200": "#ffbbce",
        "300": "#ff99b6",
        "400": "#fb779e",
        "500": "#f95587",
        "600": "#c7446c",
        "700": "#953351",
        "800": "#642236",
        "900": "#32111b",
        "950": "#19080d"
      },
      "bug": {
        "50": "#f6f8e8",
        "100": "#edf1d1",
        "200": "#dce4a3",
        "300": "#cad676",
        "400": "#b8c948",
        "500": "#a6b91a",
        "600": "#859415",
        "700": "#646f10",
        "800": "#424a0b",
        "900": "#212505",
        "950": "#101203"
      },
      "rock": {
        "50": "#f8f6eb",
        "100": "#f1ecd7",
        "200": "#e3d9af",
        "300": "#d5c687",
        "400": "#c6b35e",
        "500": "#b6a136",
        "600": "#92812b",
        "700": "#6d6120",
        "800": "#494016",
        "900": "#24200b",
        "950": "#121005"
      },
      "ghost": {
        "50": "#f1eef5",
        "100": "#e3deeb",
        "200": "#c7bdd6",
        "300": "#ab9cc2",
        "400": "#8f7bad",
        "500": "#735797",
        "600": "#5c4679",
        "700": "#45345b",
        "800": "#2e233c",
        "900": "#17111e",
        "950": "#0b090f"
      },
      "dragon": {
        "50": "#f1ebfe",
        "100": "#e2d7fe",
        "200": "#c6affd",
        "300": "#a986fc",
        "400": "#8d5dfc",
        "500": "#6f35fc",
        "600": "#592aca",
        "700": "#431f97",
        "800": "#2c1565",
        "900": "#160b32",
        "950": "#0b0519"
      },
      "steel": {
        "50": "#f8f8fa",
        "100": "#f1f1f5",
        "200": "#e2e2eb",
        "300": "#d4d4e1",
        "400": "#c5c5d8",
        "500": "#b7b7ce",
        "600": "#9292a5",
        "700": "#6e6e7c",
        "800": "#494952",
        "900": "#252529",
        "950": "#121215"
      },
      "dark": {
        "50": "#f1eeed",
        "100": "#e3dedb",
        "200": "#c6bcb7",
        "300": "#a99b93",
        "400": "#8d796e",
        "500": "#705746",
        "600": "#5a4638",
        "700": "#43342a",
        "800": "#2d231c",
        "900": "#16110e",
        "950": "#0b0907"
      },
      "fairy": {
        "50": "#fbf3f7",
        "100": "#f7e7ee",
        "200": "#efcedd",
        "300": "#e7b6cc",
        "400": "#df9dba",
        "500": "#d685ad",
        "600": "#ab6a8a",
        "700": "#805068",
        "800": "#563545",
        "900": "#2b1b23",
        "950": "#150d11"
      },
      "type": {
        "normal": "#a8a77a",
        "fire": "#ee8130",
        "water": "#6390f0",
        "electric": "#f7d02c",
        "grass": "#7ac74c",
        "ice": "#96d9d6",
        "fighting": "#c22e28",
        "poison": "#a33ea1",
        "ground": "#e2bf65",
        "flying": "#a98ff3",
        "psychic": "#f95587",
        "bug": "#a6b91a",
        "rock": "#b6a136",
        "ghost": "#735797",
        "dragon": "#6f35fc",
        "dark": "#705746",
        "steel": "#b7b7ce",
        "fairy": "#d685ad"
      },
      "bg": {
        "normal": "#f6f6f2",
        "fire": "#fef2ea",
        "water": "#eff4fe",
        "electric": "#fefbea",
        "grass": "#f2f9ed",
        "ice": "#f4fbfb",
        "fighting": "#f9eaeb",
        "poison": "#f6ecf6",
        "ground": "#fcf9f0",
        "flying": "#f6f4fe",
        "psychic": "#ffeef3",
        "bug": "#f6f8e8",
        "rock": "#f8f6eb",
        "ghost": "#f1eef5",
        "dragon": "#f1ebfe",
        "dark": "#f1eeed",
        "steel": "#f8f8fa",
        "fairy": "#fbf3f7"
      },
      "text": {
        "normal": "#656449",
        "fire": "#8f4d1d",
        "water": "#3b5690",
        "electric": "#947d1a",
        "grass": "#49772e",
        "ice": "#5a8280",
        "fighting": "#741c18",
        "poison": "#622561",
        "ground": "#88733d",
        "flying": "#655692",
        "psychic": "#953351",
        "bug": "#646f10",
        "rock": "#6d6120",
        "ghost": "#45345b",
        "dragon": "#431f97",
        "dark": "#43342a",
        "steel": "#6e6e7c",
        "fairy": "#805068"
      }
    },
    "gray": {
      "50": "#f9fafb",
      "100": "#f3f4f6",
      "200": "#e5e7eb",
      "300": "#d1d5db",
      "400": "#9ca3af",
      "500": "#6b7280",
      "600": "#4b5563",
      "700": "#374151",
      "800": "#1f2937",
      "900": "#111827",
      "950": "#030712"
    },
    "lime": {
      "50": "#f7fee7",
      "100": "#ecfccb",
      "200": "#d9f99d",
      "300": "#bef264",
      "400": "#a3e635",
      "500": "#84cc16",
      "600": "#65a30d",
      "700": "#4d7c0f",
      "800": "#3f6212",
      "900": "#365314",
      "950": "#1a2e05"
    },
    "red": {
      "50": "#fef2f2",
      "100": "#fee2e2",
      "200": "#fecaca",
      "300": "#fca5a5",
      "400": "#f87171",
      "500": "#ef4444",
      "600": "#dc2626",
      "700": "#b91c1c",
      "800": "#991b1b",
      "900": "#7f1d1d",
      "950": "#450a0a"
    },
    "white": "#ffffff",
    "black": "#000000",
    "result": {
      "win": {
        "default": "#84cc16",
        "subtle": "#ecfccb",
        "strong": "#4d7c0f"
      },
      "lose": {
        "default": "#ef4444",
        "subtle": "#fee2e2",
        "strong": "#b91c1c"
      }
    },
    "surface": {
      "page": "#f9fafb",
      "card": "#ffffff",
      "elevated": "#ffffff",
      "hovered": "#f3f4f6",
      "pressed": "#e5e7eb"
    },
    "text": {
      "primary": "#1f2937",
      "secondary": "#6b7280",
      "disabled": "#9ca3af",
      "inverse": "#ffffff"
    },
    "border": {
      "default": "#e5e7eb",
      "subtle": "#f3f4f6",
      "focused": "#4b5563"
    }
  },
  "radius": {
    "none": "0",
    "sm": "0.25rem",
    "md": "0.5rem",
    "lg": "0.75rem",
    "xl": "1rem",
    "2xl": "1.5rem",
    "full": "9999px"
  },
  "border": {
    "width": {
      "none": "0",
      "sm": "1px",
      "md": "2px",
      "lg": "4px"
    }
  },
  "shadow": {
    "none": "none",
    "sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    "md": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    "lg": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    "xl": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
    "2xl": "0 25px 50px -12px rgb(0 0 0 / 0.25)"
  },
  "duration": {
    "fast": "100ms",
    "normal": "200ms",
    "slow": "300ms",
    "slower": "500ms"
  },
  "easing": {
    "default": "cubic-bezier(0.4, 0, 0.2, 1)",
    "in": "cubic-bezier(0.4, 0, 1, 1)",
    "out": "cubic-bezier(0, 0, 0.2, 1)",
    "in-out": "cubic-bezier(0.4, 0, 0.2, 1)"
  },
  "space": {
    "0": "0",
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "8": "2rem",
    "10": "2.5rem",
    "12": "3rem",
    "16": "4rem",
    "20": "5rem"
  },
  "font": {
    "family": {
      "sans": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
      "mono": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace"
    },
    "size": {
      "xs": "0.75rem",
      "sm": "0.875rem",
      "md": "1rem",
      "lg": "1.125rem",
      "xl": "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem"
    },
    "weight": {
      "normal": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "lineHeight": {
      "tight": "1.25",
      "normal": "1.5",
      "relaxed": "1.75"
    }
  },
  "elevation": {
    "none": "none",
    "raised": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    "overlay": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    "modal": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
    "toast": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)"
  },
  "semantic-border": {
    "radius": {
      "none": "0",
      "sm": "0.25rem",
      "md": "0.5rem",
      "lg": "0.75rem",
      "pill": "9999px"
    },
    "width": {
      "none": "0",
      "default": "1px",
      "thick": "2px"
    }
  },
  "motion": {
    "duration": {
      "instant": "100ms",
      "quick": "200ms",
      "moderate": "300ms",
      "deliberate": "500ms"
    },
    "easing": {
      "default": "cubic-bezier(0.4, 0, 0.2, 1)",
      "enter": "cubic-bezier(0, 0, 0.2, 1)",
      "exit": "cubic-bezier(0.4, 0, 1, 1)"
    }
  },
  "spacing": {
    "content": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem",
      "xl": "2rem"
    },
    "layout": {
      "section": "3rem",
      "page": "4rem"
    },
    "gap": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem"
    }
  },
  "typography": {
    "heading": {
      "xl": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "2.25rem",
        "fontWeight": "700",
        "lineHeight": "1.25"
      },
      "lg": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.5rem",
        "fontWeight": "600",
        "lineHeight": "1.25"
      },
      "md": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.25rem",
        "fontWeight": "600",
        "lineHeight": "1.5"
      },
      "sm": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.125rem",
        "fontWeight": "500",
        "lineHeight": "1.5"
      }
    },
    "body": {
      "lg": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.125rem",
        "fontWeight": "400",
        "lineHeight": "1.75"
      },
      "md": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1rem",
        "fontWeight": "400",
        "lineHeight": "1.5"
      },
      "sm": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.875rem",
        "fontWeight": "400",
        "lineHeight": "1.5"
      }
    },
    "label": {
      "md": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.875rem",
        "fontWeight": "500",
        "lineHeight": "1.25"
      },
      "sm": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.75rem",
        "fontWeight": "500",
        "lineHeight": "1.25"
      },
      "xs": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.75rem",
        "fontWeight": "400",
        "lineHeight": "1.25"
      }
    },
    "code": {
      "md": {
        "fontFamily": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
        "fontSize": "0.875rem",
        "fontWeight": "400",
        "lineHeight": "1.5"
      }
    }
  },
  "badge": {
    "neutral": {
      "bg": "#f3f4f6",
      "text": "#1f2937"
    },
    "win": {
      "bg": "#ecfccb",
      "text": "#4d7c0f"
    },
    "lose": {
      "bg": "#fee2e2",
      "text": "#b91c1c"
    },
    "padding": {
      "x": "0.5rem",
      "y": "0.25rem"
    },
    "radius": "0.25rem"
  },
  "button": {
    "primary": {
      "bg": {
        "default": "#1f2937",
        "hover": "#374151",
        "pressed": "#111827",
        "disabled": "#e5e7eb"
      },
      "text": {
        "default": "#ffffff",
        "disabled": "#9ca3af"
      },
      "border": {
        "default": "#00000000",
        "focus": "#4b5563"
      }
    },
    "secondary": {
      "bg": {
        "default": "#00000000",
        "hover": "#f3f4f6",
        "pressed": "#e5e7eb",
        "disabled": "#00000000"
      },
      "text": {
        "default": "#1f2937",
        "disabled": "#9ca3af"
      },
      "border": {
        "default": "#e5e7eb",
        "hover": "#4b5563",
        "focus": "#4b5563"
      }
    },
    "ghost": {
      "bg": {
        "default": "#00000000",
        "hover": "#f3f4f6",
        "pressed": "#e5e7eb",
        "disabled": "#00000000"
      },
      "text": {
        "default": "#1f2937",
        "disabled": "#9ca3af"
      },
      "border": {
        "default": "#00000000",
        "focus": "#4b5563"
      }
    }
  },
  "card": {
    "bg": {
      "default": "#ffffff",
      "hover": "#f3f4f6"
    },
    "border": {
      "default": "#f3f4f6"
    },
    "text": {
      "title": "#1f2937",
      "body": "#6b7280"
    },
    "shadow": {
      "flat": "none",
      "raised": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      "overlay": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)"
    },
    "padding": {
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem"
    },
    "radius": "0.75rem"
  }
} as const;

/**
 * トークン型定義
 */
export type Tokens = typeof tokens;
