/**
 * Design System Tokens - components
 * @generated by Style Dictionary
 */

export const components = {
  "avatar": {
    "size": {
      "sm": "32px",
      "md": "48px",
      "lg": "80px",
      "xl": "120px"
    },
    "radius": {
      "circle": "9999px",
      "rounded": "0.75rem",
      "square": "0.25rem"
    }
  },
  "badge": {
    "neutral": {
      "bg": "#f3f4f6",
      "text": "#1f2937"
    },
    "win": {
      "bg": "#ecfccb",
      "text": "#4d7c0f"
    },
    "lose": {
      "bg": "#fee2e2",
      "text": "#b91c1c"
    },
    "padding": {
      "x": "0.5rem",
      "y": "0.25rem"
    },
    "radius": "0.25rem"
  },
  "button": {
    "primary": {
      "bg": {
        "default": "#1f2937",
        "hover": "#374151",
        "pressed": "#111827",
        "disabled": "#e5e7eb"
      },
      "text": {
        "default": "#ffffff",
        "disabled": "#9ca3af"
      },
      "border": {
        "default": "#00000000",
        "focus": "#4b5563"
      }
    },
    "secondary": {
      "bg": {
        "default": "#00000000",
        "hover": "#f3f4f6",
        "pressed": "#e5e7eb",
        "disabled": "#00000000"
      },
      "text": {
        "default": "#1f2937",
        "disabled": "#9ca3af"
      },
      "border": {
        "default": "#e5e7eb",
        "hover": "#4b5563",
        "focus": "#4b5563"
      }
    },
    "ghost": {
      "bg": {
        "default": "#00000000",
        "hover": "#f3f4f6",
        "pressed": "#e5e7eb",
        "disabled": "#00000000"
      },
      "text": {
        "default": "#1f2937",
        "disabled": "#9ca3af"
      },
      "border": {
        "default": "#00000000",
        "focus": "#4b5563"
      }
    },
    "danger": {
      "bg": {
        "default": "#ef4444",
        "hover": "#dc2626",
        "pressed": "#b91c1c",
        "disabled": "#e5e7eb"
      },
      "text": {
        "default": "#ffffff",
        "disabled": "#9ca3af"
      },
      "border": {
        "default": "#00000000",
        "focus": "#4b5563"
      }
    }
  },
  "card": {
    "bg": {
      "default": "#ffffff",
      "hover": "#f3f4f6"
    },
    "border": {
      "default": "#f3f4f6"
    },
    "text": {
      "title": "#1f2937",
      "body": "#6b7280"
    },
    "shadow": {
      "flat": "none",
      "raised": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      "overlay": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)"
    },
    "padding": {
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem"
    },
    "radius": "0.75rem"
  },
  "heading": {
    "accent": {
      "width": "6px",
      "height": "1.5rem",
      "radius": "9999px",
      "gap": "0.5rem"
    }
  }
} as const;

export type ComponentsTokens = typeof components;
