/**
 * Design System Tokens - Unified Export
 * @generated by Style Dictionary
 *
 * 使用例:
 *   import { tokens } from '@design-system/tokens';
 *   const bgColor = tokens.color.surface.page;
 *   const headingStyle = tokens.typography.heading.xl;
 */

export { colors } from './colors';
export { typography } from './typography';
export { spacing } from './spacing';
export { effects } from './effects';
export { components } from './components';

// 統合トークンオブジェクト
import { colors } from './colors';
import { typography } from './typography';
import { spacing } from './spacing';
import { effects } from './effects';
import { components } from './components';

export const tokens = {
	...colors,
	...typography,
	...spacing,
	...effects,
	...components,
} as const;

export type Tokens = typeof tokens;
