/**
 * Design System Tokens - spacing
 * @generated by Style Dictionary
 */

export const spacing = {
  "space": {
    "10": "0.25rem",
    "15": "0.375rem",
    "20": "0.5rem",
    "30": "0.75rem",
    "40": "1rem",
    "50": "1.25rem",
    "60": "1.5rem",
    "80": "2rem",
    "100": "2.5rem",
    "120": "3rem",
    "160": "4rem",
    "200": "5rem",
    "00": "0",
    "05": "0.125rem"
  },
  "spacing": {
    "content": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem",
      "xl": "2rem"
    },
    "layout": {
      "section": "3rem",
      "page": "4rem"
    },
    "gap": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem",
      "xl": "2rem"
    }
  }
} as const;

export type SpacingTokens = typeof spacing;
