/**
 * Design System Tokens - spacing
 * @generated by Style Dictionary
 */

export const spacing = {
  "space": {
    "0": "0",
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "8": "2rem",
    "10": "2.5rem",
    "12": "3rem",
    "16": "4rem",
    "20": "5rem"
  },
  "spacing": {
    "content": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem",
      "xl": "2rem"
    },
    "layout": {
      "section": "3rem",
      "page": "4rem"
    },
    "gap": {
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem"
    }
  }
} as const;

export type SpacingTokens = typeof spacing;
