/**
 * Design System Tokens - typography
 * @generated by Style Dictionary
 */

export const typography = {
  "font": {
    "family": {
      "sans": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
      "mono": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace"
    },
    "size": {
      "xs": "0.75rem",
      "sm": "0.875rem",
      "md": "1rem",
      "lg": "1.125rem",
      "xl": "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem"
    },
    "weight": {
      "normal": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "lineHeight": {
      "tight": "1.25",
      "normal": "1.5",
      "relaxed": "1.75"
    }
  },
  "typography": {
    "heading": {
      "xl": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "2.25rem",
        "fontWeight": "700",
        "lineHeight": "1.25"
      },
      "lg": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.5rem",
        "fontWeight": "600",
        "lineHeight": "1.25"
      },
      "md": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.25rem",
        "fontWeight": "600",
        "lineHeight": "1.5"
      },
      "sm": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.125rem",
        "fontWeight": "500",
        "lineHeight": "1.5"
      }
    },
    "body": {
      "lg": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1.125rem",
        "fontWeight": "400",
        "lineHeight": "1.75"
      },
      "md": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "1rem",
        "fontWeight": "400",
        "lineHeight": "1.5"
      },
      "sm": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.875rem",
        "fontWeight": "400",
        "lineHeight": "1.5"
      }
    },
    "label": {
      "md": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.875rem",
        "fontWeight": "500",
        "lineHeight": "1.25"
      },
      "sm": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.75rem",
        "fontWeight": "500",
        "lineHeight": "1.25"
      },
      "xs": {
        "fontFamily": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
        "fontSize": "0.75rem",
        "fontWeight": "400",
        "lineHeight": "1.25"
      }
    },
    "code": {
      "md": {
        "fontFamily": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
        "fontSize": "0.875rem",
        "fontWeight": "400",
        "lineHeight": "1.5"
      }
    }
  }
} as const;

export type TypographyTokens = typeof typography;
