/**
 * Chip component variant types
 * @generated by scripts/tokens/generate-types-from-tokens.mjs
 * Do not edit manually - run `npm run tokens:build` to regenerate
 */

export type ChipSize = 'sm' | 'md';

/** Available chip x variants */
export const CHIP_SIZES: ChipSize[] = ['sm', 'md'];

export type ChipRounded = 'none' | 'sm' | 'md' | 'full';

/** Available chip radius variants */
export const CHIP_ROUNDED: ChipRounded[] = ['none', 'sm', 'md', 'full'];
